services:
# Não é uma boa prática colocar a versão latest para as imagens, pois pode quebrar a aplicação.
  ebac-postgres-compose:
    image: postgres:latest
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "superSecreta"
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/data/db
    networks:
      - postgres-ebac-network

# Não é uma boa prática colocar a versão latest para as imagens, pois pode quebrar a aplicação.
  ebac-pgadmin-compose:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "eu@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "superSecreta"
    ports:
      - "16543:80"
    depends_on:
      - ebac-postgres-compose
    networks:
      - postgres-ebac-network

# Instancia do MySQL
  ebac-myaql-compose:
    image: mysql:latest
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: superSecreta
      MYSQL_ROOT_PASSWORD: superSecreta
    ports:
      - "3306:3306"
# Instancia do MondoDB
  ebac-mongo-compose:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: superSecreta
    ports:
      - "27017:27017"
    networks:
      - postgres-ebac-network
    volumes:
      - mongo_data:/data/db

volumes:
    postgres_data:

networks:
  postgres-ebac-network:
    driver: bridge